### ISSUE TITLE
Failed to use `npx` running codemod

### ISSUE THREAD

**Issue by zhanwang626** [rwjblue/codemod-cli#161]
It's follow up issue with [issue 155](https://github.com/rwjblue/codemod-cli/issues/155)
When I try to run command like: `npx -p <my-codemod> <transform-name> /some**/*glob.hbs`, it failed and error info I attached below:
```shell
zhanwang@zhanwang-mn1 a11y-codemod_trunk % npx -p @linkedin/a11y-codemod a11y-codemod remove-inline-a11y-suppression app/templates/**/*.hbs
npx: installed 395 in 10.939s
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at runTemplateTransform (/Users/zhanwang/.npm/_npx/88470/lib/node_modules/@linkedin/a11y-codemod/node_modules/codemod-cli/src/bin-support.js:62:38)
    at Object.runTransform (/Users/zhanwang/.npm/_npx/88470/lib/node_modules/@linkedin/a11y-codemod/node_modules/codemod-cli/src/bin-support.js:90:14)
    at Object.<anonymous> (/Users/zhanwang/.npm/_npx/88470/lib/node_modules/@linkedin/a11y-codemod/bin/cli.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
```

**Comment by rajasegar** [comment]
I am getting error like this while I am using my branch: https://github.com/rajasegar/codemod-cli/tree/fix-etr-bin
```
 node --inspect-brk ./bin/cli.js demo/templates/ --css=demo/css
Debugger listening on ws://127.0.0.1:9229/3d76cc6d-68d6-4218-8872-cb2a786bbbc2
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
 ERR  No files matched
(node:33874) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: /home/boot/Public/www/ember-tailwind-codemod/node_modules/.pnpm/ember-template-recast@4.3.0/node_modules/ember-template-recast/lib/bin.js -t /home/boot/Public/www/ember-tailwind-codemod/transforms/tailwind/index.js demo/templates/
    at makeError (/home/boot/Public/www/ember-tailwind-codemod/node_modules/.pnpm/execa@5.0.0/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/boot/Public/www/ember-tailwind-codemod/node_modules/.pnpm/execa@5.0.0/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:33874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...
```

**Comment by rwjblue** [comment]
Fixed by https://github.com/rwjblue/codemod-cli/commit/e57cd1a9d709c83d9788e9dfc252beb67a054b79
